### ISSUE TITLE
If no tags are specified for copy project no flags are coplied

### ISSUE THREAD

**Issue by jonmort** [launchdarkly-labs/ansible-launchdarkly-collection#16]
**Is this a support request?**
No - I have fixed this, PR incoming

**Describe the bug**
When copying a project when no tag(s) are specified no feature flags are copied

**To reproduce**
Run the following playbook with api_keys supplied
``` yaml
---

- name: Using LaunchDarkly collection to copy project
  hosts: localhost
  tasks:
    - launchdarkly_labs.collection.launchdarkly_project_copy:
        project_key: default
        project_key_dest: copy
        name: Default
```

**Expected behavior**
All feature flags to be copied

**Logs**
If applicable, add any log output related to your problem.

**SDK version**
0.2.0 of the ansible-launchdarkly-collection
